### ISSUE TITLE
About training details

### ISSUE THREAD

**Issue by zhang-haojie** [baaivision/NOVA#24]
Thank you very much for your work. I would like to know about batchsize, GPU nums, and how many iterations you set when training a NOVA from scratch?

**Comment by PhyscalX** [comment]
1. As described in our paper, we use 128 A100 (40G) GPUs.
2. For T2I training, we set batchsize 4096/2048/1024 at resolution 256/512/1024 for 300k/150k/30k iterations.
3. For T2V training, we set batchsize 512 for 80k iterations.

**Comment by zhang-haojie** [comment]
Another question, I noticed that in the training code, the design for resuming from a checkpoint uses `coordinator.get_checkpoint()` to retrieve the weights from the previous training session. However, these weights only include the `transformer`, making it impossible to load them using `pipe.from_pretrained`. May I ask if this part hasn't been fully implemented yet?

**Comment by PhyscalX** [comment]
Related issue: #13 

We use ``cfg.PIPELINE.MODULES`` to create symlinks to unchanged pipe modules. [[Code]](https://github.com/baaivision/NOVA/blob/f4524db37dfec29c10c6afcd43979bdb59311688/diffnext/pipelines/builder.py#L70).
Otherwise, you should copy unchanged modules into checkpoint directory or creating symlinks manually.

**Comment by PhyscalX** [comment]
Complete configurations:

```
PIPELINE:  
  MODULES:  
    model_index: model_zoo/nova-d48w1024-osp480/model_index.json
    scheduler: model_zoo/nova-d48w1024-osp480/scheduler
    text_encoder: model_zoo/nova-d48w1024-osp480/text_encoder
    tokenizer: model_zoo/nova-d48w1024-osp480/tokenizer
    vae: model_zoo/nova-d48w1024-osp480/vae
```

``target_path`` is not necessary, because trainer will create symlinks under ``/tmp``. [[Code]](https://github.com/baaivision/NOVA/blob/f4524db37dfec29c10c6afcd43979bdb59311688/diffnext/engine/train_engine.py#L42).
